name: Static Analysis

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Hadolint
      uses: hadolint/hadolint-action@v3.1.0  # Update to a valid version
      with:
        dockerfile: Dockerfile
