name: Static Analysis

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Hadolint
      uses: hadolint/hadolint-action@v2
      # If the above line fails, you might try specifying a different version
      # uses: hadolint/hadolint-action@v1.21.0
      # Or use an alternative linter action
      # uses: e.g. github/super-linter@v4
